### PR TITLE
Adding Typebot deployment + upgrading Botpress to Caddy

### PR DESCRIPTION
**Pull request by amiraliemami**
Reviewer: @Tanmay-97 

Estimate: 30mins

---

## Ticket

Fixes: [AAQ-367](https://idinsight.atlassian.net/browse/AAQ-367?atlOrigin=eyJpIjoiMmI3MDMyZTUxZDM0NDNjZTllNTVjNTEwOTlkNWI0MDYiLCJwIjoiaiJ9)

Also upgrades Botpress deployment to Caddy!

### Goal

- Add Typebot deployment and demo flow
- Upgrade Botpress deployment to Caddy

## How has this been tested?

- Follow the deployment instructions in the docs, under chat managers for both Botpress and Typebot

## Checklist

Fill with `x` for completed. Delete any lines that are not relevant

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my own code to ensure good quality
- [x] I have tested the functionality of my code to ensure it works as intended
- [x] I have resolved merge conflicts
- [x] I have updated affected documentation (if applicable)

[AAQ-367]: https://idinsight.atlassian.net/browse/AAQ-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Tanmay-97 — APPROVED** [review]
Great work @amiraliemami 
Could you also please add a `Typebot` section below Botpress in MKDocs.yml -> `nav/other-components`? 
Also, how can I test this? Should I run docker-compose in my local machine and check?

**Comment by amiraliemami** [comment]
> Great work @amiraliemami Could you also please add a `Typebot` section below Botpress in MKDocs.yml -> `nav/other-components`? 

Nice catch, added thanks :)

> Also, how can I test this? Should I run docker-compose in my local machine and check?

@Tanmay-97 Yes please! Try following the deployment instructions in the docs to see if you can get it working. I'll make Loom videos for the deployments if you find that it's not straight-forward.

**Comment by Tanmay-97** [comment]
Hi @amiraliemami 

I tried to run this - docker-compose command builds the containers all fine.

In the DB I get this error:
2024-02-28 18:01:27.213 UTC [55] FATAL: password authentication failed for user "postgres"
2024-02-28 18:01:27.213 UTC [55] DETAIL: Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"

In Builder I see this:
Datasource "db": PostgreSQL database "$POSTGRES_DB", schema "public" at "typebot-db:5432"
Error: P1000: Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.

❌ Invalid environment variables: {
ADMIN_EMAIL: [ 'String must contain at least 1 character(s)' ],
GITHUB_CLIENT_ID: [ 'String must contain at least 1 character(s)' ],
GITHUB_CLIENT_SECRET: [ 'String must contain at least 1 character(s)' ],
GOOGLE_CLIENT_ID: [ 'String must contain at least 1 character(s)' ],
GOOGLE_CLIENT_SECRET: [ 'String must contain at least 1 character(s)' ]
}
-- I fixed this using my GitHub creds.

But could you provide light guidance on the 1st one, and hint at resolving these 2 in the docs?

**Comment by amiraliemami** [comment]
> Hi @amiraliemami
> 
> I tried to run this - docker-compose command builds the containers all fine.
> 
> In the DB I get this error: 2024-02-28 18:01:27.213 UTC [55] FATAL: password authentication failed for user "postgres" 2024-02-28 18:01:27.213 UTC [55] DETAIL: Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
> 
> In Builder I see this: Datasource "db": PostgreSQL database "$POSTGRES_DB", schema "public" at "typebot-db:5432" Error: P1000: Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.

I wonder if this is because of some overlaps with old postgres volumes you may have on Docker... Can you delete all volumes on Docker Desktop and try again? I wonder also if it's some windows issue.

> ❌ Invalid environment variables: { ADMIN_EMAIL: [ 'String must contain at least 1 character(s)' ], GITHUB_CLIENT_ID: [ 'String must contain at least 1 character(s)' ], GITHUB_CLIENT_SECRET: [ 'String must contain at least 1 character(s)' ], GOOGLE_CLIENT_ID: [ 'String must contain at least 1 character(s)' ], GOOGLE_CLIENT_SECRET: [ 'String must contain at least 1 character(s)' ] } -- I fixed this using my GitHub creds.

Added clarifying comments to the `template.env` file - should be good now.

**Comment by Tanmay-97** [comment]
Also, please add a line describing how to go about creating GITHUB_CLIENT or GOOGLE_CLIENT, which is mandatory to make this work

For local testing, I realized I needed to setup a new Github OAuth App - could we set one up for this project? Or we could use ID and SECRET of the one I created - it redirects to `https://localhost/api/auth/callback/github`

**Pull request merged**
